server:
    port: 8761

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
    instance:
        hostname: ${spring.application.name:localhost}
        prefer-ip-address: true

# set to OFF to avoid  log "pollution" if Eureka isn't up or found 
logging:
    level:
        com:
            netflix:
                eureka: OFF
                discovery: OFF

# Spring Boot actuator
management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: "*"
                exclude: "shutdown"

